name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: bash -x build.sh
      - uses: actions/upload-artifact@v4
        with:
          path: build/app/dist/Notion-*.AppImage
