name: Build and release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Build_release:
    name: build_release
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: bash -x build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/app/dist/Notion-*.AppImage

      - name: Get Notion release version
        run: fullpath=$(ls build/app/dist/Notion-*) && binary=${fullpath/'build/app/dist/Notion-'/} && echo "::set-output name=version::${binary/.AppImage/}"
        id: version

      - name: Get latest GitHub release version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
        id: latest_release

      - name: Get current date
        if: ${{ ! contains(steps.latest_release.outputs.release, steps.version.outputs.version) }}
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create release
        if: ${{ ! contains(steps.latest_release.outputs.release, steps.version.outputs.version) }}
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ steps.version.outputs.version }} built on ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Add x86_64 to AppImage
        if: ${{ ! contains(steps.latest_release.outputs.release, steps.version.outputs.version) }}
        run: mv build/app/dist/Notion-${{ steps.version.outputs.version }}.AppImage build/app/dist/Notion-${{ steps.version.outputs.version }}-x86_64.AppImage

      - name: Upload AppImage
        if: ${{ ! contains(steps.latest_release.outputs.release, steps.version.outputs.version) }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/dist/Notion-${{ steps.version.outputs.version }}-x86_64.AppImage
          asset_name: Notion-${{ steps.version.outputs.version }}-x86_64.AppImage
          asset_content_type: application/AppImage